---
ruby/bundler-1.3.5.gem:
  object_id: eea344ef-3347-4cff-85d0-7c4cea148273
  sha: 2cad3052a59b83f1f616e8202f5c714e46bd8523
  size: 268800
ruby/ruby-2.1.5.tar.gz:
  object_id: 6bab8da8-70b7-4c24-a839-9946f34f292e
  sha: 9c0a238bd7839a4b51871641945a3da90997b8c2
  size: 15127433
ruby/rubygems-2.1.11.tgz:
  object_id: 2cb73a2e-eb0b-4726-9798-d089b618f97b
  sha: ca3033432cae28deb7ced79cda271cb292b70e59
  size: 367166
ruby/yaml-0.1.5.tar.gz:
  object_id: 6cf011d7-6362-435e-8456-2998d32edad7
  sha: 8b78cb9f759c7d80db8a7328c0ebecfe34fde737
  size: 504897
java/openjdk-jre-trusty-1.7.0_65.tar.gz/openjdk-jre-trusty-1.7.0_65.tar.gz:
  object_id: fc5be61c-2dce-4dc2-ae5d-96602320a01f
  sha: 65f4e665b0a736e861fedaa60560ba72ed19474c
  size: 31606629
